package com.ppgpt.gateway.dto;

import com.fasterxml.jackson.annotation.JsonInclude;

/**
 * Represents a tool call invocation generated by an LLM model.
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
public record ToolCallDto(
    String id,
    String type,
    FunctionCall function
) {
    public record FunctionCall(
        String name,
        String arguments
    ) {}
}
